### ISSUE TITLE
Android 11 open folder crash

### ISSUE THREAD

**Issue by xuechen628** [rosuH/AndroidFilePicker#118]
E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to get length of null array
        at me.rosuh.filepicker.utils.FileUtils$Companion.produceListDataSource(FileUtils.kt:74) <--------- (should check first if rootFile is null, maybe return an empty list)
        at me.rosuh.filepicker.FilePickerActivity.enterDirAndUpdateUI(FilePickerActivity.kt:460)
        at me.rosuh.filepicker.FilePickerActivity.onItemClick(FilePickerActivity.kt:366)
        at me.rosuh.filepicker.adapter.RecyclerViewListener$ItemTouchHelperGestureListener.onSingleTapUp(RecyclerViewListener.kt:92)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:758)
        at androidx.core.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:480)
        at androidx.core.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:543)
        at me.rosuh.filepicker.adapter.RecyclerViewListener.onInterceptTouchEvent(RecyclerViewListener.kt:68)
        at androidx.recyclerview.widget.RecyclerView.findInterceptingOnItemTouchListener(RecyclerView.java:3151)
        at androidx.recyclerview.widget.RecyclerView.onInterceptTouchEvent(RecyclerView.java:3170)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2664)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4125)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
        at android.view.View.dispatchPointerEvent(View.java:14568)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)

**Comment by rosuH** [comment]
@xuechen628 Check out whether if your  `targetAPI`  larger than 30. Do not support scope storage for now.

**Comment by xuechen628** [comment]
Hi @rosuH, thank you for your quick response, and my targetAPI = 29
folders such as document, download, etc. work fine at android 11, only some folder will throw NullPointerException at produceListDataSource(FileUtils.kt:74), I think if you can add null check will be all fine ; )

**Comment by rosuH** [comment]
That's wired... According to `java.io.File#listFiles()` 's docs:

> An array of abstract pathnames denoting the files and
     *          directories in the directory denoted by this abstract pathname.
     *          The array will be empty if the directory is empty.  Returns
     *          {@code null} if this abstract pathname does not denote a
     *          directory, or if an I/O error occurs.

If the folder is empty, `listFiles` should return an empty array. Should not return null unless the `folder` is not a true folder?

Can you confirm that? Maybe crate `File` instance for that folder and make sure `File.isDir()` returns true?.

Anyway, this is a bug and I will fix ASAP, thanks for your feedback~

**Comment by xuechen628** [comment]
that's true, but only listFiles() will return null if the path does not exist ; )

> public File[] listFiles()
> If this abstract pathname does not denote a directory, then this method returns null. 

thanks for your time and this awesome project!!!

**Comment by rosuH** [comment]
Try the latest dev version if you are available. If that works I would release one ;)
```
dependencies {
	        implementation 'com.github.rosuH:AndroidFilePicker:dev-SNAPSHOT'
	}
```

**Comment by xuechen628** [comment]
> Could not find com.github.rosuH:AndroidFilePicker:dev-SNAPSHOT.

**Comment by rosuH** [comment]
@xuechen628 Try this: `implementation 'com.github.rosuH:AndroidFilePicker:70d547a92c'`

**Comment by xuechen628** [comment]
worked perfect, you can release now! thanks a lot! 👍

**Comment by xuechen628** [comment]
already tried, worked perfectly ; ) thanks
