### ISSUE TITLE
Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'

### ISSUE THREAD

**Issue by wo122282967** [rosuH/AndroidFilePicker#43]
java.lang.IllegalStateException: Module with the Main dispatcher is missing. Add dependency providing the Main dispatcher, e.g. 'kotlinx-coroutines-android'
        at kotlinx.coroutines.internal.q.a(MainDispatchers.kt:72)
        at kotlinx.coroutines.internal.q.a(MainDispatchers.kt:53)
        at kotlinx.coroutines.ac.a(Dispatched.kt:410)
        at kotlinx.coroutines.a.a.a(Cancellable.kt:25)
        at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
        at kotlinx.coroutines.a.a(AbstractCoroutine.kt:154)
        at kotlinx.coroutines.d.a(Builders.common.kt:54)
        at kotlinx.coroutines.c.a(Unknown Source)
        at kotlinx.coroutines.d.a(Builders.common.kt:47)
        at kotlinx.coroutines.c.a(Unknown Source)
        at me.rosuh.filepicker.FilePickerActivity.g(FilePickerActivity.kt:121)
        at me.rosuh.filepicker.FilePickerActivity.onCreate(FilePickerActivity.kt:73)
        at android.app.Activity.performCreate(Activity.java:6497)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2519)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2626)
        at android.app.ActivityThread.access$1100(ActivityThread.java:170)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1494)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:179)
        at android.app.ActivityThread.main(ActivityThread.java:5769)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
09-04 17:26:25.101 1606-2697/? E/libprocessgroup: failed to kill 1 processes for processgroup 2676
09-04 17:26:25.230 2832-2832/? E/Tinker.ReflectApp: replaceApplicationLike delegateClass:class com.tencent.bugly.beta.tinker.TinkerApplicationLike
09-04 17:26:25.364 2832-2832/? E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
09-04 17:26:25.364 2832-2832/? E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0
09-04 17:26:25.364 2832-2832/? E/ExtMediaPlayer-JNI: env->IsInstanceOf fails
09-04 17:26:25.364 2832-2832/? E/MediaPlayer-JNI: JNIMediaPlayerFactory: bIsQCMediaPlayerPresent 0

**Comment by rosuH** [comment]
应该是混淆的问题，加上：
```
# ServiceLoader support
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}

# Most of volatile fields are updated with AFU and should not be mangled
-keepclassmembernames class kotlinx.** {
    volatile <fields>;
}
```

**Comment by rosuH** [comment]
@wo122282967 请问这个问题解决了吗？

> 如果您两天内不回复的话，我将会关闭此 issues，您可以在任何时候重新打开。
