### ISSUE TITLE
在Fragment中使用空指针

### ISSUE THREAD

**Issue by yi-qingqiu** [rosuH/AndroidFilePicker#48]
/**
     * 不能使用 fragment.getContext()，因为无法保证外部的代码环境
     */
    fun from(fragment: Fragment):FilePickerConfig{
        this.fragment = WeakReference(fragment)
        this.context = WeakReference(fragment.activity!!)
        return config!!
    }
在fragment 中 FilePickerConfig 是不是没有初始化？还是我使用方法不对。

**Comment by rosuH** [comment]
报错信息贴一下，如果有的话。以及调用方式

**Comment by yi-qingqiu** [comment]
在fragment中使用
调用方法 
FilePickerManager.INSTANCE
                        .from(mFragment)
                        .forResult(FilePickerManager.REQUEST_CODE);
异常 
 kotlin.KotlinNullPointerException
        at me.rosuh.filepicker.config.FilePickerManager.from(FilePickerManager.kt:37)
        at com.huateng.item.ui.financing.AddAttachmentFragment$1.onClick(AddAttachmentFragment.java:113)
        at android.view.View.performClick(View.java:5637)
        at android.view.View$PerformClick.run(View.java:22429)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

    /**
     * 不能使用 fragment.getContext()，因为无法保证外部的代码环境
     */
    fun from(fragment: Fragment): FilePickerConfig {
        this.fragment = WeakReference(fragment)
        this.context = WeakReference(fragment.activity!!)
        this.config = FilePickerConfig(this) 
  return config!!
//我在这里创建了一个FilePickerConfig 异常解决了 不知道这样对不对？
      
    }

**Comment by rosuH** [comment]
非常感谢，看起来应该是没有初始化  `config` 。
我现在在外面，估计要下午才回家着手排查和修复。

**Comment by rosuH** [comment]
已在 https://github.com/rosuH/AndroidFilePicker/commit/6a82c8874c56864ef368162a4c861bcebd55084e 中修复。
这两天会发布新版，感谢反馈。

**Comment by rosuH** [comment]
已在 [0.5.2](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.5.2) 中修复。
