### ISSUE TITLE
android 7.1.2 系统 崩溃

### ISSUE THREAD

**Issue by yuxue521** [rosuH/AndroidFilePicker#76]
点击文件夹 不崩溃  往下滑动 

`` --------- beginning of crash
2020-07-01 09:47:33.469 10502-10502/com.example.installer2 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.installer2, PID: 10502
    java.lang.NoSuchMethodError: No virtual method load(Landroid/net/Uri;)Lcom/bumptech/glide/RequestBuilder; in class Lcom/bumptech/glide/RequestManager; or its super classes (declaration of 'com.bumptech.glide.RequestManager' appears in /data/app/com.example.installer2-1/base.apk)
        at me.rosuh.filepicker.engine.GlideEngine.loadImage(GlideEngine.kt:24)
        at me.rosuh.filepicker.engine.ImageLoadController.load(ImageLoadController.kt:68)
        at me.rosuh.filepicker.adapter.FileListAdapter$FileListItemHolder.bind(FileListAdapter.kt:304)
        at me.rosuh.filepicker.adapter.FileListAdapter.onBindViewHolder(FileListAdapter.kt:74)
        at me.rosuh.filepicker.adapter.FileListAdapter.onBindViewHolder(FileListAdapter.kt:85)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6823)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6019)
        at android.support.v7.widget.GapWorker.prefetchPositionWithDeadline(GapWorker.java:286)
        at android.support.v7.widget.GapWorker.flushTaskWithDeadline(GapWorker.java:343)
        at android.support.v7.widget.GapWorker.flushTasksWithDeadline(GapWorker.java:359)
        at android.support.v7.widget.GapWorker.prefetch(GapWorker.java:366)
        at android.support.v7.widget.GapWorker.run(GapWorker.java:397)
        at android.os.Handler.handleCallback(Handler.java:755)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6141)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:912)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:802)

**Comment by rosuH** [comment]
@yuxue521 库的版本多少？您的项目里有继承 Glide 吗，有的话版本号发一下

**Comment by yuxue521** [comment]
implementation 'me.rosuh:AndroidFilePicker:0.6.3'
implementation 'com.github.bumptech.glide:glide:3.7.0'

**Comment by yuxue521** [comment]
应该是 glide的版本问题 我看你项目是4.9.0

**Comment by yuxue521** [comment]
解决了 确实 是 glide 版本的问题，我修改成跟库一致的版本 就可以了，感谢及时回复

**Comment by rosuH** [comment]
> 解决了 确实 是 glide 版本的问题，我修改成跟库一致的版本 就可以了，感谢及时回复

@yuxue521 是这个问题。因为 Glide 后期修改了 API。这块属于我判断条件不够充分，正在修复：

1. 新增自定义图片加载引擎，用于无法及时升级项目的 Glide 版本的场景
2. 调整 Glide 判断条件
3. 捕获 `NoSuchMethodError` 错误。

新版本将会在今日释出。
感谢反馈～

**Comment by rosuH** [comment]
新版本 [0.6.4](https://github.com/rosuH/AndroidFilePicker/releases/tag/0.6.4) 已经发布，欢迎体验，感谢反馈～
