### ISSUE TITLE
因框架的application文件"APP"导致的问题

### ISSUE THREAD

**Issue by prczhb** [rosuH/AndroidFilePicker#9]
背景:java代码中调用
在0.3.0 中 没有"APP" 这个application文件
故没有问题

在0.4.0中 因为框架中有"APP"这个application文件
导致与项目本身的application文件冲突,需要加入  'tools:replace="android:name"' 来解决
当加入  'tools:replace="android:name"' 解决后 调用文件选择器时,会出现如下崩溃
    kotlin.UninitializedPropertyAccessException: lateinit property appResources has not been initialized
        at me.rosuh.filepicker.App.access$getAppResources$cp(App.kt:11)
        at me.rosuh.filepicker.App$Companion.getAppResources(App.kt:14)
        at me.rosuh.filepicker.config.FilePickerConfig.<init>(FilePickerConfig.kt:34)
        at me.rosuh.filepicker.config.FilePickerManager.from(FilePickerManager.kt:30)
        at com.xxx.xxx.xxx.xxxActivity.selectDocument(xxxActivity.java:608)
        at com.xxx.xxx.xxx.xxxActivity$5.onClick(xxxActivity.java:291)
        at android.view.View.performClick(View.java:6897)
        at android.view.View$PerformClick.run(View.java:26101)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

框架中的application文件"APP" 中  appResources 未初始化? 
这难道是java代码与Kotlin代码联结的问题么?

**Comment by rosuH** [comment]
@prczhb 感谢提出 issue，看起来是设置了 `tools:replace="android:name"` 之后，框架中的 `App` 被覆盖了。
此问题应该是框架的 Bug，下午我会二次复现并尽快修复~

**Comment by rosuH** [comment]
@prczhb 已经复现并且在 https://github.com/rosuH/AndroidFilePicker/commit/77e34e75bbc34cdce1df2db22e03464d4a23467c 中修复啦。您可以使用 `0.4.1` 版本，看看问题是否解决~

**Comment by prczhb** [comment]
@rosuH 嗯,以解决,谢谢大佬
