### ISSUE TITLE
小米手机获取不到文件列表

### ISSUE THREAD

**Issue by AmoyJJ** [rosuH/AndroidFilePicker#98]
到FilePickerActivity 的loadFileRunnable 里面走没法继续走了

**Comment by rosuH** [comment]
@AmoyJJ 有报错或者更多信息吗？机型、系统、项目 targetSDK 版本这些。是否有权限？

**Comment by AmoyJJ** [comment]
K20pro  权限是有的。没有报错。也不会闪退.。就是在那转圈

**Comment by AmoyJJ** [comment]
https://github.com/GdinKing/FileSelector  换了这个工具。也是一样。
就小米系统不行。华为没问题。模拟器也没问题

**Comment by AmoyJJ** [comment]
貌似是小米获取文件地址的API更改了。我有个地方要获取存储目录的会出错
你是否有通过这类方式去获取地址？Environment.getExternalStorageDirectory().toString() + File.separator

**Comment by AmoyJJ** [comment]
FileUtils里面的getRootFile。小米无法通过那样的方式获取路径了

**Comment by AmoyJJ** [comment]
android10 的问题
在AndroidManifest.xml文件中application节点中加上android:requestLegacyExternalStorage="true"属性就可以了

**Comment by fukemy** [comment]
same problem with mi device : 
```
Build version: 1.0 Current date: 2021-02-26 10:59:38 Device: Xiaomi Redmi Note 7 OS version: Android 10 (SDK 29) Stack trace: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) Caused by: java.lang.reflect.InvocationTargetException at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) ... 1 more Caused by: java.io.FileNotFoundException: /storage/3437-3831/DCIM/Camera/IMG_20210224_081640.jpg.001: open failed: EACCES (Permission denied) at libcore.io.IoBridge.open(IoBridge.java:496) at java.io.FileOutputStream.<init>(FileOutputStream.java:235) at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
```

**Comment by rosuH** [comment]
@fukemy You should enable `android:requestLegacyExternalStorage="true"` in your `AndroidManifest.xml`.

**Comment by fukemy** [comment]
hi bro i set android:requestLegacyExternalStorage="true" in manifest
 but still got this
```
Stack trace:  
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:606)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
	... 1 more
Caused by: java.io.FileNotFoundException: /storage/emulated/0/Documents/Notes_210318_144841.txt.001: open failed: EACCES (Permission denied)
	at libcore.io.IoBridge.open(IoBridge.java:492)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
```
with samsung android 10, no problem, but this crash appear on xiaomi device

**Comment by fukemy** [comment]
my xiaomi device is android 9

**Comment by rosuH** [comment]
@fukemy Can you run the smaple app in your devices?

**Comment by fukemy** [comment]
hi, i tested and confirm your library work as expected! the problem is when i tried split this file to upload. to server, it's crash my app due to permission denied problem
```
public static List<File> splitFile(File f) throws IOException {
        int partCounter = 1;
        List<File> result = new ArrayList<>();
        int sizeOfFiles = 1024 * 1024;// 1MB
        byte[] buffer = new byte[sizeOfFiles]; // create a buffer of bytes sized as the one chunk size

        BufferedInputStream bis = new BufferedInputStream(new FileInputStream(f));
        String name = f.getName();

        int tmp = 0;
        while ((tmp = bis.read(buffer)) > 0) {
            File newFile = new File(f.getParent(), name + "." + String.format("%03d", partCounter++)); // naming files as <inputFileName>.001, <inputFileName>.002, ...
            if(!newFile.canRead()){
                return new ArrayList<>();
            }
            FileOutputStream out = new FileOutputStream(newFile);
            out.write(buffer, 0, tmp);//tmp is chunk size. Need it for the last chunk, which could be less then 1 mb.
            result.add(newFile);
        }
        return result;
    }
```
i dont know why i occur, may be some connection. to this file is still alive,... can u help? Thanks in advance

**Comment by fukemy** [comment]
ok, before split file i ask 2 permission programmatically then problem disappear, dont know why ( because your library asked this problem before open file activity)
```
PermissionManager.getInstance().requestPermissions(this@ChatScreen, arrayOf(
                        Manifest.permission.READ_EXTERNAL_STORAGE,
                        Manifest.permission.WRITE_EXTERNAL_STORAGE), object :
                        IListPermissionListener {
                        override fun onGranted() {
                            val uuid = UUID.randomUUID().toString()
                            val mockMessage = MockMessage(uuid, AppUtil.currentMockUser(), null, Date())
                            mockMessage.image = MockMessage.Image(FileUtils.getUriToResource(this@ChatScreen, R.mipmap.ic_file_preview).toString())
                            messagesAdapter.addToStart(mockMessage, true)

                            uploadFile(files, FileUtils.getMimeType(this@ChatScreen, list.first().toString()), uuid)
                        }

                        override fun onRefused(permissions: List<Permission?>?) {
                        }
                    })
```

**Comment by rosuH** [comment]
😄  The lib just requests the `READ_EXTERNAL_STORAGE `...So you need to request the `WRITE_EXTERNAL_STROAGE` by yourself.

https://github.com/rosuH/AndroidFilePicker/blob/6b684e4c2fbf23fc49692f0a30aead019a69e2be/filepicker/src/main/java/me/rosuh/filepicker/FilePickerActivity.kt#L149-L163
